# -*- coding: utf-8 -*-
"""Submit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eZzjvU1h4TkvRB7QR9_72aF1z9e07BKj
"""

import numpy as np
import sklearn

# You are allowed to import any submodules of numpy or sklearn e.g. sklearn.metrics.accuracy_score to calculate accuracy of a learnt model
# You are not allowed to use other libraries such as scipy, keras, tensorflow etc

# SUBMIT YOUR CODE AS A SINGLE PYTHON (.PY) FILE INSIDE A ZIP ARCHIVE
# THE NAME OF THE PYTHON FILE MUST BE submit.py

# DO NOT CHANGE THE NAME OF THE METHODS my_map, my_params etc BELOW
# THESE WILL BE INVOKED BY THE EVALUATION SCRIPT. CHANGING THESE NAMES WILL CAUSE EVALUATION FAILURE

# You may define any new functions, variables, classes here

################################
# Non Editable Region Starting #
################################
def my_map( X ):
################################
#  Non Editable Region Ending  #
################################

    # Use this method to map raw features to proper embeddings
    # Your embeddings will be used to train a linear SVM model

    """
    PUF computes m = c XOR s, then:
        he = sum of even-indexed bits of m
        ho = sum of odd-indexed  bits of m
        response = 1 if he*ho >= t else 0

    Since m_k = c_k + s_k - 2*c_k*s_k,
     Substituting into he and ho:
            he = (linear combination of even bits of c) + constant
            ho = (linear combination of odd  bits of c) + constant

        Multiplying out he * ho produces 4 types of terms:
            (1) even_bit * odd_bit   => needs 16x16=256 cross product features
            (2) even_bit * constant  => needs 16 even bit features
            (3) odd_bit  * constant  => needs 16 odd  bit features
            (4) constant * constant  => needs 1 bias feature

    Feature map (D = 289):
        bias(1) + original bits(32) + cross terms even_i*odd_j (256)
        captures TERM4 + TERM2 and 3 + TERM1 respectively
    """

    # separate even and odd bits
    even_idx  = np.arange(0, 32, 2)    # 16 even indices
    odd_idx   = np.arange(1, 32, 2)    # 16 odd indices
    even_bits = X[:, even_idx]         # (N, 16) even bits
    odd_bits  = X[:, odd_idx]          # (N, 16) odd bits

    # all 16x16=256 cross products even_i*odd_j
    cross_terms = (even_bits[:, :, None] * odd_bits[:, None, :]).reshape(X.shape[0], -1)

    # bias term (captures constant K_e*K_o)
    bias = np.ones((X.shape[0], 1))

    # concatenate bias(1) + all bits(32) + cross terms(256) = 289 dims
    X_map = np.concatenate([bias, X, cross_terms], axis=1)

    return X_map


################################
# Non Editable Region Starting #
################################
def my_params( X_map, X_raw, y ):
################################
#  Non Editable Region Ending  #
################################

    """
    Hardcoded hyperparameters for maximum speed marks.
    C=1.0 found best via cross-validation over [0.0001 ... 100.0].
    dual=False preferred when n_samples(7500) >> n_features(289).
    """

    my_params = {
        'C'        : 1.0,             # best C found via cross-validation
        'dual'     : False,           # primal solver; faster when n_samples >> n_features
        'tol'      : 1e-4,            # convergence tolerance
        'max_iter' : 5000,            # max iterations to ensure convergence
        'loss'     : 'squared_hinge', # smooth loss; required for dual=False
    }

    return my_params